spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOriginPatterns:
              - "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      default-filters:
        - RemoveRequestHeader=Origin

      routes:
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**,/api/me/**,/api/organizations/**
        - id: course-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/courses/**,/api/enrollments/**,/api/quizzes/**,/api/media/**
        - id: core-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/core/**
          filters:
            - RewritePath=/api/core/(?<segment>.*), /$\{segment}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
